In [1]:
# Import pandas and geopandas
import pandas as pd
import geopandas as gpd

In [3]:
# use wget to download the GLODAPv2.2023 master file zip archive "GLODAPv2.2023_Merged_Master_File.csv.zip"
!wget https://glodap.info/glodap_files/v2.2023/GLODAPv2.2023_Merged_Master_File.csv.zip

--2024-07-04 16:44:18--  https://glodap.info/glodap_files/v2.2023/GLODAPv2.2023_Merged_Master_File.csv.zip
Resolving glodap.info (glodap.info)... 212.201.155.241
Connecting to glodap.info (glodap.info)|212.201.155.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110353886 (105M) [application/zip]
Saving to: ‘GLODAPv2.2023_Merged_Master_File.csv.zip’

GLODAPv2.2023_Merge 100%[===================>] 105.24M  11.2MB/s    in 9.6s

2024-07-04 16:44:28 (10.9 MB/s) - ‘GLODAPv2.2023_Merged_Master_File.csv.zip’ saved [110353886/110353886]

In [4]:
# Load Glodap data into a pandas dataframe 
# hinting at datatypes in the glodap csv file fields

df = pd.read_csv('GLODAPv2.2023_Merged_Master_File.csv.zip',dtype={'G2expocode' : str, 'G2Cruise' : int, 'G2region' :int , 'G2cast' :int ,'G2year': int,'G2month' : int,'G2day' : int,	'G2hour': int, 'G2minute' : int, 'G2bottle' : int, 'G2doi' : str})

In [5]:
# examine the data frame
df.head(10)

,G2expocode,G2cruise,G2station,G2region,G2cast,G2year,G2month,G2day,G2hour,G2minute,...,G2tocf,G2doc,G2docf,G2don,G2donf,G2tdn,G2tdnf,G2chla,G2chlaf,G2doi
0,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
1,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
2,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
3,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
4,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
5,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
6,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
7,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
8,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...
9,06AQ19840719,1.0,319.0,4,1,1984,7,20,14,46,...,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,https://doi.org/10.3334/cdiac/otg.carina_06aq1...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1402829 entries, 0 to 1402828
Columns: 109 entries, G2expocode to G2doi
dtypes: float64(99), int64(8), object(2)
memory usage: 1.1+ GB

In [7]:
# Remove the first 2 "G2" characters from column names
df.columns = df.columns.str[2:]
# examine the fields and sample data
print(df.head())

       expocode  cruise  station  region  cast  year  month  day  hour  \
0  06AQ19840719     1.0    319.0       4     1  1984      7   20    14
1  06AQ19840719     1.0    319.0       4     1  1984      7   20    14
2  06AQ19840719     1.0    319.0       4     1  1984      7   20    14
3  06AQ19840719     1.0    319.0       4     1  1984      7   20    14
4  06AQ19840719     1.0    319.0       4     1  1984      7   20    14

   minute  ...  tocf     doc  docf     don  donf     tdn  tdnf    chla  chlaf  \
0      46  ...   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0    9.0
1      46  ...   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0    9.0
2      46  ...   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0    9.0
3      46  ...   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0    9.0
4      46  ...   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0   9.0 -9999.0    9.0

                                                 doi
0  https://doi.org/10.3334/cdiac/otg.carina_06aq1...
1  https://doi.org/10.3334/cdiac/otg.carina_06aq1...
2  https://doi.org/10.3334/cdiac/otg.carina_06aq1...
3  https://doi.org/10.3334/cdiac/otg.carina_06aq1...
4  https://doi.org/10.3334/cdiac/otg.carina_06aq1...

[5 rows x 109 columns]

In [8]:
# Combine year, month, day, hour, and minute columns into a new datetime column
df['recordedtime'] = pd.to_datetime(df[['year', 'month', 'day', 'hour', 'minute']])

In [9]:
from shapely.geometry import Point

# Create a GeoPandas GeoDataFrame with Point geometries
gdf = gpd.GeoDataFrame(df, 
                        geometry=gpd.points_from_xy(df['longitude'], df['latitude']),
                        crs='EPSG:4326')  # Set the coordinate reference system (CRS)

In [10]:
# Install the pyarrow library dependency for geoparquet export from geopandas
%pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-16.1.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.11/site-packages (from pyarrow) (1.26.4)
Downloading pyarrow-16.1.0-cp311-cp311-manylinux_2_28_x86_64.whl (40.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 9.6 MB/s eta 0:00:00:00:0100:01
Installing collected packages: pyarrow
Successfully installed pyarrow-16.1.0
Note: you may need to restart the kernel to use updated packages.

In [11]:
# export the geopandas dataframe as geoparquet
gdf.to_parquet('glodap_v2_2023_merged_master.parquet')

In [12]:
# show the local directory workspace contents to see the new geoparquet file
%ls

GLODAPv2.2023_Merged_Master_File.csv.zip  glodap_v2_2023_merged_master.parquet
glodap_to_geoparquet.ipynb                work/

In [ ]:
#GLODAPv2.2023

#Olsen, A., R. M. Key, S. van Heuven, S. K. Lauvset, A. Velo, X. Lin, C. Schirnick, A. Kozyr, T. Tanhua, M. Hoppema, S. Jutterström, R. Steinfeldt,
#E. Jeansson, M. Ishii, F. F. Pérez and T. Suzuki. The Global Ocean Data Analysis Project version 2 (GLODAPv2) – an internally consistent data
#product for the world ocean, Earth Syst. Sci. Data, 8, 297–323, 2016, doi:10.5194/essd-8-297-2016

#Lauvset, S. K, R. M. Key, A. Olsen, S. van Heuven, A. Velo, X. Lin, C. Schirnick, A. Kozyr, T. Tanhua, M. Hoppema, S. Jutterström, R. Steinfeldt, E.
#Jeansson, M. Ishii, F. F. Pérez, T. Suzuki and S. Watelet. A new global interior ocean mapped climatology: the 1°x1° GLODAP version 2, Earth Syst.
#Sci. Data, 8, 325–340, 2016, doi:10.5194/essd-8-325-2016

#Key, R.M., A. Olsen, S. van Heuven, S. K. Lauvset, A. Velo, X. Lin, C. Schirnick, A. Kozyr, T. Tanhua, M. Hoppema, S. Jutterström, R. Steinfeldt, E.
#Jeansson, M. Ishii, F. F. Perez, and T. Suzuki. 2015. Global Ocean Data Analysis Project, Version 2 (GLODAPv2), ORNL/CDIAC-162, NDP-093. Carbon
#Dioxide Information Analysis Center, Oak Ridge National Laboratory, US Department of Energy, Oak Ridge, Tennessee. doi:10.3334/CDIAC/OTG.
#NDP093_GLODAPv2